// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: iam/authz/v4/authz.proto

package authzv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationMode int32

const (
	AuthorizationMode_AUTHORIZATION_MODE_UNSPECIFIED AuthorizationMode = 0
	AuthorizationMode_UNCONDITIONAL                  AuthorizationMode = 1
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	AuthorizationMode_OBJECT_CHECK_REQUIRED AuthorizationMode = 2
)

// Enum value maps for AuthorizationMode.
var (
	AuthorizationMode_name = map[int32]string{
		0: "AUTHORIZATION_MODE_UNSPECIFIED",
		1: "UNCONDITIONAL",
		2: "OBJECT_CHECK_REQUIRED",
	}
	AuthorizationMode_value = map[string]int32{
		"AUTHORIZATION_MODE_UNSPECIFIED": 0,
		"UNCONDITIONAL":                  1,
		"OBJECT_CHECK_REQUIRED":          2,
	}
)

func (x AuthorizationMode) Enum() *AuthorizationMode {
	p := new(AuthorizationMode)
	*p = x
	return p
}

func (x AuthorizationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authz_v4_authz_proto_enumTypes[0].Descriptor()
}

func (AuthorizationMode) Type() protoreflect.EnumType {
	return &file_iam_authz_v4_authz_proto_enumTypes[0]
}

func (x AuthorizationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationMode.Descriptor instead.
func (AuthorizationMode) EnumDescriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{0}
}

type DecisionReason int32

const (
	DecisionReason_DECISION_REASON_UNSPECIFIED DecisionReason = 0
	DecisionReason_ALLOWED                     DecisionReason = 1
	DecisionReason_NOT_MATCHED                 DecisionReason = 2
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	DecisionReason_ATTRIBUTE_MISSING DecisionReason = 3
)

// Enum value maps for DecisionReason.
var (
	DecisionReason_name = map[int32]string{
		0: "DECISION_REASON_UNSPECIFIED",
		1: "ALLOWED",
		2: "NOT_MATCHED",
		3: "ATTRIBUTE_MISSING",
	}
	DecisionReason_value = map[string]int32{
		"DECISION_REASON_UNSPECIFIED": 0,
		"ALLOWED":                     1,
		"NOT_MATCHED":                 2,
		"ATTRIBUTE_MISSING":           3,
	}
)

func (x DecisionReason) Enum() *DecisionReason {
	p := new(DecisionReason)
	*p = x
	return p
}

func (x DecisionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authz_v4_authz_proto_enumTypes[1].Descriptor()
}

func (DecisionReason) Type() protoreflect.EnumType {
	return &file_iam_authz_v4_authz_proto_enumTypes[1]
}

func (x DecisionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionReason.Descriptor instead.
func (DecisionReason) EnumDescriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{1}
}

type DataScopeKind int32

const (
	DataScopeKind_DATA_SCOPE_KIND_UNSPECIFIED DataScopeKind = 0
	DataScopeKind_ALL_STORES                  DataScopeKind = 1
	DataScopeKind_STORES                      DataScopeKind = 2
)

// Enum value maps for DataScopeKind.
var (
	DataScopeKind_name = map[int32]string{
		0: "DATA_SCOPE_KIND_UNSPECIFIED",
		1: "ALL_STORES",
		2: "STORES",
	}
	DataScopeKind_value = map[string]int32{
		"DATA_SCOPE_KIND_UNSPECIFIED": 0,
		"ALL_STORES":                  1,
		"STORES":                      2,
	}
)

func (x DataScopeKind) Enum() *DataScopeKind {
	p := new(DataScopeKind)
	*p = x
	return p
}

func (x DataScopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataScopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authz_v4_authz_proto_enumTypes[2].Descriptor()
}

func (DataScopeKind) Type() protoreflect.EnumType {
	return &file_iam_authz_v4_authz_proto_enumTypes[2]
}

func (x DataScopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataScopeKind.Descriptor instead.
func (DataScopeKind) EnumDescriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
type ObjectAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ObjectAttribute_StringValue
	//	*ObjectAttribute_Int64Value
	//	*ObjectAttribute_BoolValue
	Value         isObjectAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectAttribute) Reset() {
	*x = ObjectAttribute{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAttribute) ProtoMessage() {}

func (x *ObjectAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAttribute.ProtoReflect.Descriptor instead.
func (*ObjectAttribute) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectAttribute) GetValue() isObjectAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ObjectAttribute) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ObjectAttribute) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *ObjectAttribute) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isObjectAttribute_Value interface {
	isObjectAttribute_Value()
}

type ObjectAttribute_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ObjectAttribute_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type ObjectAttribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*ObjectAttribute_StringValue) isObjectAttribute_Value() {}

func (*ObjectAttribute_Int64Value) isObjectAttribute_Value() {}

func (*ObjectAttribute_BoolValue) isObjectAttribute_Value() {}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
type ObjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Attributes    []*ObjectAttribute     `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectContext) Reset() {
	*x = ObjectContext{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectContext) ProtoMessage() {}

func (x *ObjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectContext.ProtoReflect.Descriptor instead.
func (*ObjectContext) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectContext) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectContext) GetAttributes() []*ObjectAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Subject  string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	ObjectContext *ObjectContext `protobuf:"bytes,5,opt,name=object_context,json=objectContext,proto3" json:"object_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
func (x *CheckRequest) GetObjectContext() *ObjectContext {
	if x != nil {
		return x.ObjectContext
	}
	return nil
}

type CheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason         DecisionReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=iam.authz.v4.DecisionReason" json:"reason,omitempty"`
	DenyCode       string                 `protobuf:"bytes,3,opt,name=deny_code,json=denyCode,proto3" json:"deny_code,omitempty"`
	MatchedGrantId string                 `protobuf:"bytes,4,opt,name=matched_grant_id,json=matchedGrantId,proto3" json:"matched_grant_id,omitempty"`
	MatchedRole    string                 `protobuf:"bytes,5,opt,name=matched_role,json=matchedRole,proto3" json:"matched_role,omitempty"`
	PolicyVersion  int64                  `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	MissingAttributeKeys []string `protobuf:"bytes,7,rep,name=missing_attribute_keys,json=missingAttributeKeys,proto3" json:"missing_attribute_keys,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() DecisionReason {
	if x != nil {
		return x.Reason
	}
	return DecisionReason_DECISION_REASON_UNSPECIFIED
}

func (x *CheckResponse) GetDenyCode() string {
	if x != nil {
		return x.DenyCode
	}
	return ""
}

func (x *CheckResponse) GetMatchedGrantId() string {
	if x != nil {
		return x.MatchedGrantId
	}
	return ""
}

func (x *CheckResponse) GetMatchedRole() string {
	if x != nil {
		return x.MatchedRole
	}
	return ""
}

func (x *CheckResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
func (x *CheckResponse) GetMissingAttributeKeys() []string {
	if x != nil {
		return x.MissingAttributeKeys
	}
	return nil
}

// One company-specific range. Empty/missing scopes never imply unrestricted data.
type DataScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Kind          DataScopeKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=iam.authz.v4.DataScopeKind" json:"kind,omitempty"`
	StoreIds      []string               `protobuf:"bytes,3,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataScope) Reset() {
	*x = DataScope{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataScope) ProtoMessage() {}

func (x *DataScope) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataScope.ProtoReflect.Descriptor instead.
func (*DataScope) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{4}
}

func (x *DataScope) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DataScope) GetKind() DataScopeKind {
	if x != nil {
		return x.Kind
	}
	return DataScopeKind_DATA_SCOPE_KIND_UNSPECIFIED
}

func (x *DataScope) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

type PermissionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Mode          AuthorizationMode      `protobuf:"varint,3,opt,name=mode,proto3,enum=iam.authz.v4.AuthorizationMode" json:"mode,omitempty"`
	Scopes        []*DataScope           `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionEntry) Reset() {
	*x = PermissionEntry{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionEntry) ProtoMessage() {}

func (x *PermissionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionEntry.ProtoReflect.Descriptor instead.
func (*PermissionEntry) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionEntry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionEntry) GetMode() AuthorizationMode {
	if x != nil {
		return x.Mode
	}
	return AuthorizationMode_AUTHORIZATION_MODE_UNSPECIFIED
}

func (x *PermissionEntry) GetScopes() []*DataScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type GetAuthorizationSnapshotRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Subject string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AppName string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Restricted to callers admitted to managed assignment replacement.
	IncludeAssignmentFacts bool `protobuf:"varint,4,opt,name=include_assignment_facts,json=includeAssignmentFacts,proto3" json:"include_assignment_facts,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAuthorizationSnapshotRequest) Reset() {
	*x = GetAuthorizationSnapshotRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationSnapshotRequest) ProtoMessage() {}

func (x *GetAuthorizationSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthorizationSnapshotRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetAuthorizationSnapshotRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetAuthorizationSnapshotRequest) GetIncludeAssignmentFacts() bool {
	if x != nil {
		return x.IncludeAssignmentFacts
	}
	return false
}

type GetAuthorizationSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roles contains the directly assigned roles for app_name, identical to direct_roles.
	Roles         []string           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []*PermissionEntry `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PolicyVersion int64              `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// direct_roles contains only assignments directly bound to the subject.
	DirectRoles []string `protobuf:"bytes,4,rep,name=direct_roles,json=directRoles,proto3" json:"direct_roles,omitempty"`
	// Full direct role facts, including other applications and global roles.
	AssignmentFacts         []*AssignmentRoleFact `protobuf:"bytes,5,rep,name=assignment_facts,json=assignmentFacts,proto3" json:"assignment_facts,omitempty"`
	AssignmentFactsComplete bool                  `protobuf:"varint,6,opt,name=assignment_facts_complete,json=assignmentFactsComplete,proto3" json:"assignment_facts_complete,omitempty"`
	// 1 means scopes are paired with each permission. 0 is an older producer;
	// consumers requiring data scope must reject it rather than assume all stores.
	ScopeContractVersion uint32 `protobuf:"varint,7,opt,name=scope_contract_version,json=scopeContractVersion,proto3" json:"scope_contract_version,omitempty"`
	// Per-assignment facts, supplied only with authorized include_assignment_facts.
	AssignmentScopes []*AssignmentScopeFact `protobuf:"bytes,8,rep,name=assignment_scopes,json=assignmentScopes,proto3" json:"assignment_scopes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAuthorizationSnapshotResponse) Reset() {
	*x = GetAuthorizationSnapshotResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationSnapshotResponse) ProtoMessage() {}

func (x *GetAuthorizationSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuthorizationSnapshotResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetPermissions() []*PermissionEntry {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *GetAuthorizationSnapshotResponse) GetDirectRoles() []string {
	if x != nil {
		return x.DirectRoles
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetAssignmentFacts() []*AssignmentRoleFact {
	if x != nil {
		return x.AssignmentFacts
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetAssignmentFactsComplete() bool {
	if x != nil {
		return x.AssignmentFactsComplete
	}
	return false
}

func (x *GetAuthorizationSnapshotResponse) GetScopeContractVersion() uint32 {
	if x != nil {
		return x.ScopeContractVersion
	}
	return 0
}

func (x *GetAuthorizationSnapshotResponse) GetAssignmentScopes() []*AssignmentScopeFact {
	if x != nil {
		return x.AssignmentScopes
	}
	return nil
}

type GrantAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	GrantedBy     string                 `protobuf:"bytes,4,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAssignmentRequest) Reset() {
	*x = GrantAssignmentRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAssignmentRequest) ProtoMessage() {}

func (x *GrantAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GrantAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{8}
}

func (x *GrantAssignmentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GrantAssignmentRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GrantAssignmentRequest) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

type GrantAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyVersion int64                  `protobuf:"varint,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAssignmentResponse) Reset() {
	*x = GrantAssignmentResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAssignmentResponse) ProtoMessage() {}

func (x *GrantAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GrantAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{9}
}

func (x *GrantAssignmentResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type RevokeAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RevokedBy     string                 `protobuf:"bytes,4,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAssignmentRequest) Reset() {
	*x = RevokeAssignmentRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAssignmentRequest) ProtoMessage() {}

func (x *RevokeAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAssignmentRequest.ProtoReflect.Descriptor instead.
func (*RevokeAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAssignmentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyVersion int64                  `protobuf:"varint,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAssignmentResponse) Reset() {
	*x = RevokeAssignmentResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAssignmentResponse) ProtoMessage() {}

func (x *RevokeAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAssignmentResponse.ProtoReflect.Descriptor instead.
func (*RevokeAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeAssignmentResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type ReplaceManagedAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleNames     []string               `protobuf:"bytes,3,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceManagedAssignmentsRequest) Reset() {
	*x = ReplaceManagedAssignmentsRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceManagedAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceManagedAssignmentsRequest) ProtoMessage() {}

func (x *ReplaceManagedAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceManagedAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ReplaceManagedAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceManagedAssignmentsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ReplaceManagedAssignmentsRequest) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

func (x *ReplaceManagedAssignmentsRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ReplaceManagedAssignmentsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplaceManagedAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectRoles   []string               `protobuf:"bytes,1,rep,name=direct_roles,json=directRoles,proto3" json:"direct_roles,omitempty"`
	PolicyVersion int64                  `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Changed       bool                   `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceManagedAssignmentsResponse) Reset() {
	*x = ReplaceManagedAssignmentsResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceManagedAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceManagedAssignmentsResponse) ProtoMessage() {}

func (x *ReplaceManagedAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceManagedAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ReplaceManagedAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{13}
}

func (x *ReplaceManagedAssignmentsResponse) GetDirectRoles() []string {
	if x != nil {
		return x.DirectRoles
	}
	return nil
}

func (x *ReplaceManagedAssignmentsResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ReplaceManagedAssignmentsResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type AssignmentRoleFact struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RoleId               string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ManagementProtection string                 `protobuf:"bytes,3,opt,name=management_protection,json=managementProtection,proto3" json:"management_protection,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssignmentRoleFact) Reset() {
	*x = AssignmentRoleFact{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentRoleFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentRoleFact) ProtoMessage() {}

func (x *AssignmentRoleFact) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentRoleFact.ProtoReflect.Descriptor instead.
func (*AssignmentRoleFact) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{14}
}

func (x *AssignmentRoleFact) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignmentRoleFact) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AssignmentRoleFact) GetManagementProtection() string {
	if x != nil {
		return x.ManagementProtection
	}
	return ""
}

type ScopedRoleAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Scope         *DataScope             `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopedRoleAssignment) Reset() {
	*x = ScopedRoleAssignment{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopedRoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopedRoleAssignment) ProtoMessage() {}

func (x *ScopedRoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopedRoleAssignment.ProtoReflect.Descriptor instead.
func (*ScopedRoleAssignment) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{15}
}

func (x *ScopedRoleAssignment) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ScopedRoleAssignment) GetScope() *DataScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ReplaceScopedAssignmentsRequest struct {
	state     protoimpl.MessageState  `protogen:"open.v1"`
	Subject   string                  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	OrgId     string                  `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Roles     []*ScopedRoleAssignment `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	ChangedBy string                  `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	Reason    string                  `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optimistic management edit guard; checked under the write transaction lock.
	ExpectedPolicyVersion int64 `protobuf:"varint,6,opt,name=expected_policy_version,json=expectedPolicyVersion,proto3" json:"expected_policy_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReplaceScopedAssignmentsRequest) Reset() {
	*x = ReplaceScopedAssignmentsRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceScopedAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceScopedAssignmentsRequest) ProtoMessage() {}

func (x *ReplaceScopedAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceScopedAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ReplaceScopedAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{16}
}

func (x *ReplaceScopedAssignmentsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ReplaceScopedAssignmentsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ReplaceScopedAssignmentsRequest) GetRoles() []*ScopedRoleAssignment {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ReplaceScopedAssignmentsRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ReplaceScopedAssignmentsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReplaceScopedAssignmentsRequest) GetExpectedPolicyVersion() int64 {
	if x != nil {
		return x.ExpectedPolicyVersion
	}
	return 0
}

type AssignmentScopeFact struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Role         *AssignmentRoleFact    `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Absent means unconfigured, never all stores.
	Scope         *DataScope `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentScopeFact) Reset() {
	*x = AssignmentScopeFact{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentScopeFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentScopeFact) ProtoMessage() {}

func (x *AssignmentScopeFact) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentScopeFact.ProtoReflect.Descriptor instead.
func (*AssignmentScopeFact) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{17}
}

func (x *AssignmentScopeFact) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *AssignmentScopeFact) GetRole() *AssignmentRoleFact {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *AssignmentScopeFact) GetScope() *DataScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_iam_authz_v4_authz_proto protoreflect.FileDescriptor

const file_iam_authz_v4_authz_proto_rawDesc = "" +
	"\n" +
	"\x18iam/authz/v4/authz.proto\x12\fiam.authz.v4\"\x99\x01\n" +
	"\x0fObjectAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue:\x02\x18\x01B\a\n" +
	"\x05value\"o\n" +
	"\rObjectContext\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12=\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\x1d.iam.authz.v4.ObjectAttributeR\n" +
	"attributes:\x02\x18\x01\"\xb2\x01\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12F\n" +
	"\x0eobject_context\x18\x05 \x01(\v2\x1b.iam.authz.v4.ObjectContextB\x02\x18\x01R\robjectContextJ\x04\b\x02\x10\x03R\x06domain\"\xaa\x02\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1c.iam.authz.v4.DecisionReasonR\x06reason\x12\x1b\n" +
	"\tdeny_code\x18\x03 \x01(\tR\bdenyCode\x12(\n" +
	"\x10matched_grant_id\x18\x04 \x01(\tR\x0ematchedGrantId\x12!\n" +
	"\fmatched_role\x18\x05 \x01(\tR\vmatchedRole\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x03R\rpolicyVersion\x128\n" +
	"\x16missing_attribute_keys\x18\a \x03(\tB\x02\x18\x01R\x14missingAttributeKeys\"p\n" +
	"\tDataScope\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.iam.authz.v4.DataScopeKindR\x04kind\x12\x1b\n" +
	"\tstore_ids\x18\x03 \x03(\tR\bstoreIds\"\xab\x01\n" +
	"\x0fPermissionEntry\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x123\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1f.iam.authz.v4.AuthorizationModeR\x04mode\x12/\n" +
	"\x06scopes\x18\x04 \x03(\v2\x17.iam.authz.v4.DataScopeR\x06scopes\"\x9e\x01\n" +
	"\x1fGetAuthorizationSnapshotRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x128\n" +
	"\x18include_assignment_facts\x18\x04 \x01(\bR\x16includeAssignmentFactsJ\x04\b\x02\x10\x03R\x06domain\"\xd2\x03\n" +
	" GetAuthorizationSnapshotResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\x12?\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1d.iam.authz.v4.PermissionEntryR\vpermissions\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x03R\rpolicyVersion\x12!\n" +
	"\fdirect_roles\x18\x04 \x03(\tR\vdirectRoles\x12K\n" +
	"\x10assignment_facts\x18\x05 \x03(\v2 .iam.authz.v4.AssignmentRoleFactR\x0fassignmentFacts\x12:\n" +
	"\x19assignment_facts_complete\x18\x06 \x01(\bR\x17assignmentFactsComplete\x124\n" +
	"\x16scope_contract_version\x18\a \x01(\rR\x14scopeContractVersion\x12N\n" +
	"\x11assignment_scopes\x18\b \x03(\v2!.iam.authz.v4.AssignmentScopeFactR\x10assignmentScopes\"|\n" +
	"\x16GrantAssignmentRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x04 \x01(\tR\tgrantedByJ\x04\b\x02\x10\x03R\x06domain\"@\n" +
	"\x17GrantAssignmentResponse\x12%\n" +
	"\x0epolicy_version\x18\x01 \x01(\x03R\rpolicyVersion\"\x95\x01\n" +
	"\x17RevokeAssignmentRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x04 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonJ\x04\b\x02\x10\x03R\x06domain\"A\n" +
	"\x18RevokeAssignmentResponse\x12%\n" +
	"\x0epolicy_version\x18\x01 \x01(\x03R\rpolicyVersion\"\xa0\x01\n" +
	" ReplaceManagedAssignmentsRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"role_names\x18\x03 \x03(\tR\troleNames\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonJ\x04\b\x02\x10\x03R\x06domain\"\x87\x01\n" +
	"!ReplaceManagedAssignmentsResponse\x12!\n" +
	"\fdirect_roles\x18\x01 \x03(\tR\vdirectRoles\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\x03R\rpolicyVersion\x12\x18\n" +
	"\achanged\x18\x03 \x01(\bR\achanged\"\x7f\n" +
	"\x12AssignmentRoleFact\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x123\n" +
	"\x15management_protection\x18\x03 \x01(\tR\x14managementProtection\"b\n" +
	"\x14ScopedRoleAssignment\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12-\n" +
	"\x05scope\x18\x02 \x01(\v2\x17.iam.authz.v4.DataScopeR\x05scope\"\xfb\x01\n" +
	"\x1fReplaceScopedAssignmentsRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x128\n" +
	"\x05roles\x18\x03 \x03(\v2\".iam.authz.v4.ScopedRoleAssignmentR\x05roles\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x126\n" +
	"\x17expected_policy_version\x18\x06 \x01(\x03R\x15expectedPolicyVersion\"\x9f\x01\n" +
	"\x13AssignmentScopeFact\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x124\n" +
	"\x04role\x18\x02 \x01(\v2 .iam.authz.v4.AssignmentRoleFactR\x04role\x12-\n" +
	"\x05scope\x18\x03 \x01(\v2\x17.iam.authz.v4.DataScopeR\x05scope*i\n" +
	"\x11AuthorizationMode\x12\"\n" +
	"\x1eAUTHORIZATION_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rUNCONDITIONAL\x10\x01\x12\x1d\n" +
	"\x15OBJECT_CHECK_REQUIRED\x10\x02\x1a\x02\b\x01*j\n" +
	"\x0eDecisionReason\x12\x1f\n" +
	"\x1bDECISION_REASON_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aALLOWED\x10\x01\x12\x0f\n" +
	"\vNOT_MATCHED\x10\x02\x12\x19\n" +
	"\x11ATTRIBUTE_MISSING\x10\x03\x1a\x02\b\x01*L\n" +
	"\rDataScopeKind\x12\x1f\n" +
	"\x1bDATA_SCOPE_KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ALL_STORES\x10\x01\x12\n" +
	"\n" +
	"\x06STORES\x10\x022\x90\x05\n" +
	"\x14AuthorizationService\x12@\n" +
	"\x05Check\x12\x1a.iam.authz.v4.CheckRequest\x1a\x1b.iam.authz.v4.CheckResponse\x12y\n" +
	"\x18GetAuthorizationSnapshot\x12-.iam.authz.v4.GetAuthorizationSnapshotRequest\x1a..iam.authz.v4.GetAuthorizationSnapshotResponse\x12^\n" +
	"\x0fGrantAssignment\x12$.iam.authz.v4.GrantAssignmentRequest\x1a%.iam.authz.v4.GrantAssignmentResponse\x12a\n" +
	"\x10RevokeAssignment\x12%.iam.authz.v4.RevokeAssignmentRequest\x1a&.iam.authz.v4.RevokeAssignmentResponse\x12|\n" +
	"\x19ReplaceManagedAssignments\x12..iam.authz.v4.ReplaceManagedAssignmentsRequest\x1a/.iam.authz.v4.ReplaceManagedAssignmentsResponse\x12z\n" +
	"\x18ReplaceScopedAssignments\x12-.iam.authz.v4.ReplaceScopedAssignmentsRequest\x1a/.iam.authz.v4.ReplaceManagedAssignmentsResponseB>Z<github.com/FangcunMount/iam/v5/api/grpc/iam/authz/v4;authzv4b\x06proto3"

var (
	file_iam_authz_v4_authz_proto_rawDescOnce sync.Once
	file_iam_authz_v4_authz_proto_rawDescData []byte
)

func file_iam_authz_v4_authz_proto_rawDescGZIP() []byte {
	file_iam_authz_v4_authz_proto_rawDescOnce.Do(func() {
		file_iam_authz_v4_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_authz_v4_authz_proto_rawDesc), len(file_iam_authz_v4_authz_proto_rawDesc)))
	})
	return file_iam_authz_v4_authz_proto_rawDescData
}

var file_iam_authz_v4_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_iam_authz_v4_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_iam_authz_v4_authz_proto_goTypes = []any{
	(AuthorizationMode)(0),                    // 0: iam.authz.v4.AuthorizationMode
	(DecisionReason)(0),                       // 1: iam.authz.v4.DecisionReason
	(DataScopeKind)(0),                        // 2: iam.authz.v4.DataScopeKind
	(*ObjectAttribute)(nil),                   // 3: iam.authz.v4.ObjectAttribute
	(*ObjectContext)(nil),                     // 4: iam.authz.v4.ObjectContext
	(*CheckRequest)(nil),                      // 5: iam.authz.v4.CheckRequest
	(*CheckResponse)(nil),                     // 6: iam.authz.v4.CheckResponse
	(*DataScope)(nil),                         // 7: iam.authz.v4.DataScope
	(*PermissionEntry)(nil),                   // 8: iam.authz.v4.PermissionEntry
	(*GetAuthorizationSnapshotRequest)(nil),   // 9: iam.authz.v4.GetAuthorizationSnapshotRequest
	(*GetAuthorizationSnapshotResponse)(nil),  // 10: iam.authz.v4.GetAuthorizationSnapshotResponse
	(*GrantAssignmentRequest)(nil),            // 11: iam.authz.v4.GrantAssignmentRequest
	(*GrantAssignmentResponse)(nil),           // 12: iam.authz.v4.GrantAssignmentResponse
	(*RevokeAssignmentRequest)(nil),           // 13: iam.authz.v4.RevokeAssignmentRequest
	(*RevokeAssignmentResponse)(nil),          // 14: iam.authz.v4.RevokeAssignmentResponse
	(*ReplaceManagedAssignmentsRequest)(nil),  // 15: iam.authz.v4.ReplaceManagedAssignmentsRequest
	(*ReplaceManagedAssignmentsResponse)(nil), // 16: iam.authz.v4.ReplaceManagedAssignmentsResponse
	(*AssignmentRoleFact)(nil),                // 17: iam.authz.v4.AssignmentRoleFact
	(*ScopedRoleAssignment)(nil),              // 18: iam.authz.v4.ScopedRoleAssignment
	(*ReplaceScopedAssignmentsRequest)(nil),   // 19: iam.authz.v4.ReplaceScopedAssignmentsRequest
	(*AssignmentScopeFact)(nil),               // 20: iam.authz.v4.AssignmentScopeFact
}
var file_iam_authz_v4_authz_proto_depIdxs = []int32{
	3,  // 0: iam.authz.v4.ObjectContext.attributes:type_name -> iam.authz.v4.ObjectAttribute
	4,  // 1: iam.authz.v4.CheckRequest.object_context:type_name -> iam.authz.v4.ObjectContext
	1,  // 2: iam.authz.v4.CheckResponse.reason:type_name -> iam.authz.v4.DecisionReason
	2,  // 3: iam.authz.v4.DataScope.kind:type_name -> iam.authz.v4.DataScopeKind
	0,  // 4: iam.authz.v4.PermissionEntry.mode:type_name -> iam.authz.v4.AuthorizationMode
	7,  // 5: iam.authz.v4.PermissionEntry.scopes:type_name -> iam.authz.v4.DataScope
	8,  // 6: iam.authz.v4.GetAuthorizationSnapshotResponse.permissions:type_name -> iam.authz.v4.PermissionEntry
	17, // 7: iam.authz.v4.GetAuthorizationSnapshotResponse.assignment_facts:type_name -> iam.authz.v4.AssignmentRoleFact
	20, // 8: iam.authz.v4.GetAuthorizationSnapshotResponse.assignment_scopes:type_name -> iam.authz.v4.AssignmentScopeFact
	7,  // 9: iam.authz.v4.ScopedRoleAssignment.scope:type_name -> iam.authz.v4.DataScope
	18, // 10: iam.authz.v4.ReplaceScopedAssignmentsRequest.roles:type_name -> iam.authz.v4.ScopedRoleAssignment
	17, // 11: iam.authz.v4.AssignmentScopeFact.role:type_name -> iam.authz.v4.AssignmentRoleFact
	7,  // 12: iam.authz.v4.AssignmentScopeFact.scope:type_name -> iam.authz.v4.DataScope
	5,  // 13: iam.authz.v4.AuthorizationService.Check:input_type -> iam.authz.v4.CheckRequest
	9,  // 14: iam.authz.v4.AuthorizationService.GetAuthorizationSnapshot:input_type -> iam.authz.v4.GetAuthorizationSnapshotRequest
	11, // 15: iam.authz.v4.AuthorizationService.GrantAssignment:input_type -> iam.authz.v4.GrantAssignmentRequest
	13, // 16: iam.authz.v4.AuthorizationService.RevokeAssignment:input_type -> iam.authz.v4.RevokeAssignmentRequest
	15, // 17: iam.authz.v4.AuthorizationService.ReplaceManagedAssignments:input_type -> iam.authz.v4.ReplaceManagedAssignmentsRequest
	19, // 18: iam.authz.v4.AuthorizationService.ReplaceScopedAssignments:input_type -> iam.authz.v4.ReplaceScopedAssignmentsRequest
	6,  // 19: iam.authz.v4.AuthorizationService.Check:output_type -> iam.authz.v4.CheckResponse
	10, // 20: iam.authz.v4.AuthorizationService.GetAuthorizationSnapshot:output_type -> iam.authz.v4.GetAuthorizationSnapshotResponse
	12, // 21: iam.authz.v4.AuthorizationService.GrantAssignment:output_type -> iam.authz.v4.GrantAssignmentResponse
	14, // 22: iam.authz.v4.AuthorizationService.RevokeAssignment:output_type -> iam.authz.v4.RevokeAssignmentResponse
	16, // 23: iam.authz.v4.AuthorizationService.ReplaceManagedAssignments:output_type -> iam.authz.v4.ReplaceManagedAssignmentsResponse
	16, // 24: iam.authz.v4.AuthorizationService.ReplaceScopedAssignments:output_type -> iam.authz.v4.ReplaceManagedAssignmentsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_iam_authz_v4_authz_proto_init() }
func file_iam_authz_v4_authz_proto_init() {
	if File_iam_authz_v4_authz_proto != nil {
		return
	}
	file_iam_authz_v4_authz_proto_msgTypes[0].OneofWrappers = []any{
		(*ObjectAttribute_StringValue)(nil),
		(*ObjectAttribute_Int64Value)(nil),
		(*ObjectAttribute_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_authz_v4_authz_proto_rawDesc), len(file_iam_authz_v4_authz_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_authz_v4_authz_proto_goTypes,
		DependencyIndexes: file_iam_authz_v4_authz_proto_depIdxs,
		EnumInfos:         file_iam_authz_v4_authz_proto_enumTypes,
		MessageInfos:      file_iam_authz_v4_authz_proto_msgTypes,
	}.Build()
	File_iam_authz_v4_authz_proto = out.File
	file_iam_authz_v4_authz_proto_goTypes = nil
	file_iam_authz_v4_authz_proto_depIdxs = nil
}
