#!/usr/bin/env sh
set -eu

SERVICE="${SERVICE:-apiserver}"

case "$SERVICE" in
  apiserver|iam|iam-apiserver)
    SERVICE=apiserver
    IMAGE_NAME=iam
    DOCKERFILE=build/docker/Dockerfile
    COMPOSE_SERVICE=iam-apiserver
    CONTAINER_NAME=iam-apiserver
    PACKAGE_SUFFIX=apiserver
    INTERNAL_HTTP_PORT="${INTERNAL_HTTP_PORT:-9080}"
    HEALTH_PATH="${HEALTH_PATH:-/healthz}"
    READINESS_PATH="${READINESS_PATH:-/readyz}"
    ;;
  *)
    echo "Unsupported SERVICE: $SERVICE" >&2
    exit 1
    ;;
esac

DEPLOY_PACKAGE="${DEPLOY_PACKAGE:-deploy-package-${PACKAGE_SUFFIX}.tar.gz}"
PKG_PATH="${PKG_PATH:-/tmp/${DEPLOY_PACKAGE}}"

export SERVICE IMAGE_NAME DOCKERFILE COMPOSE_SERVICE CONTAINER_NAME PACKAGE_SUFFIX DEPLOY_PACKAGE PKG_PATH
export INTERNAL_HTTP_PORT HEALTH_PATH READINESS_PATH

iam_probe_gate_allows() {
  [ "${1:-}" = "200" ] && [ "${2:-}" = "200" ]
}

if [ "${IMAGE_METADATA_PRINT:-}" = "1" ]; then
  cat <<EOF
SERVICE=${SERVICE}
IMAGE_NAME=${IMAGE_NAME}
DOCKERFILE=${DOCKERFILE}
COMPOSE_SERVICE=${COMPOSE_SERVICE}
CONTAINER_NAME=${CONTAINER_NAME}
PACKAGE_SUFFIX=${PACKAGE_SUFFIX}
DEPLOY_PACKAGE=${DEPLOY_PACKAGE}
PKG_PATH=${PKG_PATH}
INTERNAL_HTTP_PORT=${INTERNAL_HTTP_PORT}
HEALTH_PATH=${HEALTH_PATH}
READINESS_PATH=${READINESS_PATH}
EOF
fi
