// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: iam/identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityRead_GetUser_FullMethodName          = "/iam.identity.v1.IdentityRead/GetUser"
	IdentityRead_BatchGetUsers_FullMethodName    = "/iam.identity.v1.IdentityRead/BatchGetUsers"
	IdentityRead_SearchUsers_FullMethodName      = "/iam.identity.v1.IdentityRead/SearchUsers"
	IdentityRead_GetProfile_FullMethodName       = "/iam.identity.v1.IdentityRead/GetProfile"
	IdentityRead_BatchGetProfiles_FullMethodName = "/iam.identity.v1.IdentityRead/BatchGetProfiles"
)

// IdentityReadClient is the client API for IdentityRead service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityReadClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error)
	SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	BatchGetProfiles(ctx context.Context, in *BatchGetProfilesRequest, opts ...grpc.CallOption) (*BatchGetProfilesResponse, error)
}

type identityReadClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityReadClient(cc grpc.ClientConnInterface) IdentityReadClient {
	return &identityReadClient{cc}
}

func (c *identityReadClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, IdentityRead_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityReadClient) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetUsersResponse)
	err := c.cc.Invoke(ctx, IdentityRead_BatchGetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityReadClient) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResponse)
	err := c.cc.Invoke(ctx, IdentityRead_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityReadClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, IdentityRead_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityReadClient) BatchGetProfiles(ctx context.Context, in *BatchGetProfilesRequest, opts ...grpc.CallOption) (*BatchGetProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetProfilesResponse)
	err := c.cc.Invoke(ctx, IdentityRead_BatchGetProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityReadServer is the server API for IdentityRead service.
// All implementations must embed UnimplementedIdentityReadServer
// for forward compatibility.
type IdentityReadServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	BatchGetUsers(context.Context, *BatchGetUsersRequest) (*BatchGetUsersResponse, error)
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	BatchGetProfiles(context.Context, *BatchGetProfilesRequest) (*BatchGetProfilesResponse, error)
	mustEmbedUnimplementedIdentityReadServer()
}

// UnimplementedIdentityReadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityReadServer struct{}

func (UnimplementedIdentityReadServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedIdentityReadServer) BatchGetUsers(context.Context, *BatchGetUsersRequest) (*BatchGetUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetUsers not implemented")
}
func (UnimplementedIdentityReadServer) SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedIdentityReadServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedIdentityReadServer) BatchGetProfiles(context.Context, *BatchGetProfilesRequest) (*BatchGetProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetProfiles not implemented")
}
func (UnimplementedIdentityReadServer) mustEmbedUnimplementedIdentityReadServer() {}
func (UnimplementedIdentityReadServer) testEmbeddedByValue()                      {}

// UnsafeIdentityReadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityReadServer will
// result in compilation errors.
type UnsafeIdentityReadServer interface {
	mustEmbedUnimplementedIdentityReadServer()
}

func RegisterIdentityReadServer(s grpc.ServiceRegistrar, srv IdentityReadServer) {
	// If the following call panics, it indicates UnimplementedIdentityReadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityRead_ServiceDesc, srv)
}

func _IdentityRead_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityReadServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityRead_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityReadServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityRead_BatchGetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityReadServer).BatchGetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityRead_BatchGetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityReadServer).BatchGetUsers(ctx, req.(*BatchGetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityRead_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityReadServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityRead_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityReadServer).SearchUsers(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityRead_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityReadServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityRead_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityReadServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityRead_BatchGetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityReadServer).BatchGetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityRead_BatchGetProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityReadServer).BatchGetProfiles(ctx, req.(*BatchGetProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityRead_ServiceDesc is the grpc.ServiceDesc for IdentityRead service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityRead_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.identity.v1.IdentityRead",
	HandlerType: (*IdentityReadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _IdentityRead_GetUser_Handler,
		},
		{
			MethodName: "BatchGetUsers",
			Handler:    _IdentityRead_BatchGetUsers_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _IdentityRead_SearchUsers_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _IdentityRead_GetProfile_Handler,
		},
		{
			MethodName: "BatchGetProfiles",
			Handler:    _IdentityRead_BatchGetProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/identity/v1/identity.proto",
}

const (
	ProfileLinkQuery_HasProfileLink_FullMethodName   = "/iam.identity.v1.ProfileLinkQuery/HasProfileLink"
	ProfileLinkQuery_ListProfiles_FullMethodName     = "/iam.identity.v1.ProfileLinkQuery/ListProfiles"
	ProfileLinkQuery_ListProfileLinks_FullMethodName = "/iam.identity.v1.ProfileLinkQuery/ListProfileLinks"
)

// ProfileLinkQueryClient is the client API for ProfileLinkQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileLinkQueryClient interface {
	HasProfileLink(ctx context.Context, in *HasProfileLinkRequest, opts ...grpc.CallOption) (*HasProfileLinkResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	ListProfileLinks(ctx context.Context, in *ListProfileLinksRequest, opts ...grpc.CallOption) (*ListProfileLinksResponse, error)
}

type profileLinkQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileLinkQueryClient(cc grpc.ClientConnInterface) ProfileLinkQueryClient {
	return &profileLinkQueryClient{cc}
}

func (c *profileLinkQueryClient) HasProfileLink(ctx context.Context, in *HasProfileLinkRequest, opts ...grpc.CallOption) (*HasProfileLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasProfileLinkResponse)
	err := c.cc.Invoke(ctx, ProfileLinkQuery_HasProfileLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileLinkQueryClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, ProfileLinkQuery_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileLinkQueryClient) ListProfileLinks(ctx context.Context, in *ListProfileLinksRequest, opts ...grpc.CallOption) (*ListProfileLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfileLinksResponse)
	err := c.cc.Invoke(ctx, ProfileLinkQuery_ListProfileLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileLinkQueryServer is the server API for ProfileLinkQuery service.
// All implementations must embed UnimplementedProfileLinkQueryServer
// for forward compatibility.
type ProfileLinkQueryServer interface {
	HasProfileLink(context.Context, *HasProfileLinkRequest) (*HasProfileLinkResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	ListProfileLinks(context.Context, *ListProfileLinksRequest) (*ListProfileLinksResponse, error)
	mustEmbedUnimplementedProfileLinkQueryServer()
}

// UnimplementedProfileLinkQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileLinkQueryServer struct{}

func (UnimplementedProfileLinkQueryServer) HasProfileLink(context.Context, *HasProfileLinkRequest) (*HasProfileLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasProfileLink not implemented")
}
func (UnimplementedProfileLinkQueryServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedProfileLinkQueryServer) ListProfileLinks(context.Context, *ListProfileLinksRequest) (*ListProfileLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfileLinks not implemented")
}
func (UnimplementedProfileLinkQueryServer) mustEmbedUnimplementedProfileLinkQueryServer() {}
func (UnimplementedProfileLinkQueryServer) testEmbeddedByValue()                          {}

// UnsafeProfileLinkQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileLinkQueryServer will
// result in compilation errors.
type UnsafeProfileLinkQueryServer interface {
	mustEmbedUnimplementedProfileLinkQueryServer()
}

func RegisterProfileLinkQueryServer(s grpc.ServiceRegistrar, srv ProfileLinkQueryServer) {
	// If the following call panics, it indicates UnimplementedProfileLinkQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileLinkQuery_ServiceDesc, srv)
}

func _ProfileLinkQuery_HasProfileLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasProfileLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkQueryServer).HasProfileLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkQuery_HasProfileLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkQueryServer).HasProfileLink(ctx, req.(*HasProfileLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileLinkQuery_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkQueryServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkQuery_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkQueryServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileLinkQuery_ListProfileLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfileLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkQueryServer).ListProfileLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkQuery_ListProfileLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkQueryServer).ListProfileLinks(ctx, req.(*ListProfileLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileLinkQuery_ServiceDesc is the grpc.ServiceDesc for ProfileLinkQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileLinkQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.identity.v1.ProfileLinkQuery",
	HandlerType: (*ProfileLinkQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasProfileLink",
			Handler:    _ProfileLinkQuery_HasProfileLink_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ProfileLinkQuery_ListProfiles_Handler,
		},
		{
			MethodName: "ListProfileLinks",
			Handler:    _ProfileLinkQuery_ListProfileLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/identity/v1/identity.proto",
}

const (
	ProfileLinkCommand_CreateProfileLink_FullMethodName       = "/iam.identity.v1.ProfileLinkCommand/CreateProfileLink"
	ProfileLinkCommand_RevokeProfileLink_FullMethodName       = "/iam.identity.v1.ProfileLinkCommand/RevokeProfileLink"
	ProfileLinkCommand_BatchRevokeProfileLinks_FullMethodName = "/iam.identity.v1.ProfileLinkCommand/BatchRevokeProfileLinks"
	ProfileLinkCommand_ImportProfileLinks_FullMethodName      = "/iam.identity.v1.ProfileLinkCommand/ImportProfileLinks"
)

// ProfileLinkCommandClient is the client API for ProfileLinkCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileLinkCommandClient interface {
	CreateProfileLink(ctx context.Context, in *CreateProfileLinkRequest, opts ...grpc.CallOption) (*CreateProfileLinkResponse, error)
	RevokeProfileLink(ctx context.Context, in *RevokeProfileLinkRequest, opts ...grpc.CallOption) (*RevokeProfileLinkResponse, error)
	BatchRevokeProfileLinks(ctx context.Context, in *BatchRevokeProfileLinksRequest, opts ...grpc.CallOption) (*BatchRevokeProfileLinksResponse, error)
	ImportProfileLinks(ctx context.Context, in *ImportProfileLinksRequest, opts ...grpc.CallOption) (*ImportProfileLinksResponse, error)
}

type profileLinkCommandClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileLinkCommandClient(cc grpc.ClientConnInterface) ProfileLinkCommandClient {
	return &profileLinkCommandClient{cc}
}

func (c *profileLinkCommandClient) CreateProfileLink(ctx context.Context, in *CreateProfileLinkRequest, opts ...grpc.CallOption) (*CreateProfileLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileLinkResponse)
	err := c.cc.Invoke(ctx, ProfileLinkCommand_CreateProfileLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileLinkCommandClient) RevokeProfileLink(ctx context.Context, in *RevokeProfileLinkRequest, opts ...grpc.CallOption) (*RevokeProfileLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeProfileLinkResponse)
	err := c.cc.Invoke(ctx, ProfileLinkCommand_RevokeProfileLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileLinkCommandClient) BatchRevokeProfileLinks(ctx context.Context, in *BatchRevokeProfileLinksRequest, opts ...grpc.CallOption) (*BatchRevokeProfileLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRevokeProfileLinksResponse)
	err := c.cc.Invoke(ctx, ProfileLinkCommand_BatchRevokeProfileLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileLinkCommandClient) ImportProfileLinks(ctx context.Context, in *ImportProfileLinksRequest, opts ...grpc.CallOption) (*ImportProfileLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportProfileLinksResponse)
	err := c.cc.Invoke(ctx, ProfileLinkCommand_ImportProfileLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileLinkCommandServer is the server API for ProfileLinkCommand service.
// All implementations must embed UnimplementedProfileLinkCommandServer
// for forward compatibility.
type ProfileLinkCommandServer interface {
	CreateProfileLink(context.Context, *CreateProfileLinkRequest) (*CreateProfileLinkResponse, error)
	RevokeProfileLink(context.Context, *RevokeProfileLinkRequest) (*RevokeProfileLinkResponse, error)
	BatchRevokeProfileLinks(context.Context, *BatchRevokeProfileLinksRequest) (*BatchRevokeProfileLinksResponse, error)
	ImportProfileLinks(context.Context, *ImportProfileLinksRequest) (*ImportProfileLinksResponse, error)
	mustEmbedUnimplementedProfileLinkCommandServer()
}

// UnimplementedProfileLinkCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileLinkCommandServer struct{}

func (UnimplementedProfileLinkCommandServer) CreateProfileLink(context.Context, *CreateProfileLinkRequest) (*CreateProfileLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfileLink not implemented")
}
func (UnimplementedProfileLinkCommandServer) RevokeProfileLink(context.Context, *RevokeProfileLinkRequest) (*RevokeProfileLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeProfileLink not implemented")
}
func (UnimplementedProfileLinkCommandServer) BatchRevokeProfileLinks(context.Context, *BatchRevokeProfileLinksRequest) (*BatchRevokeProfileLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRevokeProfileLinks not implemented")
}
func (UnimplementedProfileLinkCommandServer) ImportProfileLinks(context.Context, *ImportProfileLinksRequest) (*ImportProfileLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportProfileLinks not implemented")
}
func (UnimplementedProfileLinkCommandServer) mustEmbedUnimplementedProfileLinkCommandServer() {}
func (UnimplementedProfileLinkCommandServer) testEmbeddedByValue()                            {}

// UnsafeProfileLinkCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileLinkCommandServer will
// result in compilation errors.
type UnsafeProfileLinkCommandServer interface {
	mustEmbedUnimplementedProfileLinkCommandServer()
}

func RegisterProfileLinkCommandServer(s grpc.ServiceRegistrar, srv ProfileLinkCommandServer) {
	// If the following call panics, it indicates UnimplementedProfileLinkCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileLinkCommand_ServiceDesc, srv)
}

func _ProfileLinkCommand_CreateProfileLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkCommandServer).CreateProfileLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkCommand_CreateProfileLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkCommandServer).CreateProfileLink(ctx, req.(*CreateProfileLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileLinkCommand_RevokeProfileLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeProfileLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkCommandServer).RevokeProfileLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkCommand_RevokeProfileLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkCommandServer).RevokeProfileLink(ctx, req.(*RevokeProfileLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileLinkCommand_BatchRevokeProfileLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRevokeProfileLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkCommandServer).BatchRevokeProfileLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkCommand_BatchRevokeProfileLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkCommandServer).BatchRevokeProfileLinks(ctx, req.(*BatchRevokeProfileLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileLinkCommand_ImportProfileLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportProfileLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileLinkCommandServer).ImportProfileLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileLinkCommand_ImportProfileLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileLinkCommandServer).ImportProfileLinks(ctx, req.(*ImportProfileLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileLinkCommand_ServiceDesc is the grpc.ServiceDesc for ProfileLinkCommand service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileLinkCommand_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.identity.v1.ProfileLinkCommand",
	HandlerType: (*ProfileLinkCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfileLink",
			Handler:    _ProfileLinkCommand_CreateProfileLink_Handler,
		},
		{
			MethodName: "RevokeProfileLink",
			Handler:    _ProfileLinkCommand_RevokeProfileLink_Handler,
		},
		{
			MethodName: "BatchRevokeProfileLinks",
			Handler:    _ProfileLinkCommand_BatchRevokeProfileLinks_Handler,
		},
		{
			MethodName: "ImportProfileLinks",
			Handler:    _ProfileLinkCommand_ImportProfileLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/identity/v1/identity.proto",
}

const (
	IdentityLifecycle_CreateUser_FullMethodName     = "/iam.identity.v1.IdentityLifecycle/CreateUser"
	IdentityLifecycle_UpdateUser_FullMethodName     = "/iam.identity.v1.IdentityLifecycle/UpdateUser"
	IdentityLifecycle_DeactivateUser_FullMethodName = "/iam.identity.v1.IdentityLifecycle/DeactivateUser"
	IdentityLifecycle_BlockUser_FullMethodName      = "/iam.identity.v1.IdentityLifecycle/BlockUser"
)

// IdentityLifecycleClient is the client API for IdentityLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityLifecycleClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeactivateUser(ctx context.Context, in *ChangeUserStatusRequest, opts ...grpc.CallOption) (*UserOperationResponse, error)
	BlockUser(ctx context.Context, in *ChangeUserStatusRequest, opts ...grpc.CallOption) (*UserOperationResponse, error)
}

type identityLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityLifecycleClient(cc grpc.ClientConnInterface) IdentityLifecycleClient {
	return &identityLifecycleClient{cc}
}

func (c *identityLifecycleClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, IdentityLifecycle_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityLifecycleClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, IdentityLifecycle_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityLifecycleClient) DeactivateUser(ctx context.Context, in *ChangeUserStatusRequest, opts ...grpc.CallOption) (*UserOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOperationResponse)
	err := c.cc.Invoke(ctx, IdentityLifecycle_DeactivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityLifecycleClient) BlockUser(ctx context.Context, in *ChangeUserStatusRequest, opts ...grpc.CallOption) (*UserOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOperationResponse)
	err := c.cc.Invoke(ctx, IdentityLifecycle_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityLifecycleServer is the server API for IdentityLifecycle service.
// All implementations must embed UnimplementedIdentityLifecycleServer
// for forward compatibility.
type IdentityLifecycleServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeactivateUser(context.Context, *ChangeUserStatusRequest) (*UserOperationResponse, error)
	BlockUser(context.Context, *ChangeUserStatusRequest) (*UserOperationResponse, error)
	mustEmbedUnimplementedIdentityLifecycleServer()
}

// UnimplementedIdentityLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityLifecycleServer struct{}

func (UnimplementedIdentityLifecycleServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedIdentityLifecycleServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedIdentityLifecycleServer) DeactivateUser(context.Context, *ChangeUserStatusRequest) (*UserOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateUser not implemented")
}
func (UnimplementedIdentityLifecycleServer) BlockUser(context.Context, *ChangeUserStatusRequest) (*UserOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedIdentityLifecycleServer) mustEmbedUnimplementedIdentityLifecycleServer() {}
func (UnimplementedIdentityLifecycleServer) testEmbeddedByValue()                           {}

// UnsafeIdentityLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityLifecycleServer will
// result in compilation errors.
type UnsafeIdentityLifecycleServer interface {
	mustEmbedUnimplementedIdentityLifecycleServer()
}

func RegisterIdentityLifecycleServer(s grpc.ServiceRegistrar, srv IdentityLifecycleServer) {
	// If the following call panics, it indicates UnimplementedIdentityLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityLifecycle_ServiceDesc, srv)
}

func _IdentityLifecycle_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityLifecycleServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityLifecycle_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityLifecycleServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityLifecycle_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityLifecycleServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityLifecycle_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityLifecycleServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityLifecycle_DeactivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityLifecycleServer).DeactivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityLifecycle_DeactivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityLifecycleServer).DeactivateUser(ctx, req.(*ChangeUserStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityLifecycle_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityLifecycleServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityLifecycle_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityLifecycleServer).BlockUser(ctx, req.(*ChangeUserStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityLifecycle_ServiceDesc is the grpc.ServiceDesc for IdentityLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.identity.v1.IdentityLifecycle",
	HandlerType: (*IdentityLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _IdentityLifecycle_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IdentityLifecycle_UpdateUser_Handler,
		},
		{
			MethodName: "DeactivateUser",
			Handler:    _IdentityLifecycle_DeactivateUser_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _IdentityLifecycle_BlockUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/identity/v1/identity.proto",
}
