-- Enforce one active RoleBinding for the same subject, role, and tenant.
-- active_guard is generated by MySQL, so every write path is protected even
-- when it does not go through the GORM persistence object. Duplicate active
-- rows make unique-index creation fail closed; no authorization fact is deleted.

SET @iam_has_active_guard = (
    SELECT COUNT(*)
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'authz_assignments'
      AND COLUMN_NAME = 'active_guard'
);
SET @iam_sql = IF(
    @iam_has_active_guard = 0,
    'ALTER TABLE `authz_assignments` ADD COLUMN `active_guard` TINYINT GENERATED ALWAYS AS (CASE WHEN `deleted_at` IS NULL THEN 1 ELSE NULL END) STORED COMMENT ''active RoleBinding 唯一性保护'' AFTER `tenant_id`',
    'SELECT 1'
);
PREPARE iam_stmt FROM @iam_sql;
EXECUTE iam_stmt;
DEALLOCATE PREPARE iam_stmt;

SET @iam_has_active_index = (
    SELECT COUNT(*)
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'authz_assignments'
      AND INDEX_NAME = 'uk_authz_assignments_active'
);
SET @iam_sql = IF(
    @iam_has_active_index = 0,
    'CREATE UNIQUE INDEX `uk_authz_assignments_active` ON `authz_assignments` (`subject_type`, `subject_id`, `role_id`, `tenant_id`, `active_guard`)',
    'SELECT 1'
);
PREPARE iam_stmt FROM @iam_sql;
EXECUTE iam_stmt;
DEALLOCATE PREPARE iam_stmt;
