//go:build reliable_messaging

package integration_test

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	appuow "github.com/FangcunMount/iam/v5/internal/apiserver/application/authz/uow"
	domainpolicy "github.com/FangcunMount/iam/v5/internal/apiserver/domain/authz/policy"
	domainrole "github.com/FangcunMount/iam/v5/internal/apiserver/domain/authz/role"
	"github.com/FangcunMount/iam/v5/internal/apiserver/infra/mysql/eventoutbox"
	policyrepo "github.com/FangcunMount/iam/v5/internal/apiserver/infra/mysql/policy"
	rolerepo "github.com/FangcunMount/iam/v5/internal/apiserver/infra/mysql/role"
	authzuow "github.com/FangcunMount/iam/v5/internal/apiserver/infra/mysql/uow/authz"
	"github.com/FangcunMount/iam/v5/internal/apiserver/testfixtures/authzdb"
	dbmysql "github.com/FangcunMount/iam/v5/internal/pkg/database/mysql"
	"github.com/FangcunMount/reliable-messaging/message"
	"github.com/FangcunMount/reliable-messaging/outbox"
	sdkmysql "github.com/FangcunMount/reliable-messaging/storage/mysql"
	"github.com/stretchr/testify/require"
)

// This proof intentionally writes a comparison SDK row and a real historical
// row in one isolated transaction. It is not a deployed dual-publish design.
func TestReliableMessagingOriginalUoW(t *testing.T) {
	if os.Getenv("IAM_AUTHZ_TEST_MYSQL_DSN") == "" {
		t.Fatal("isolated MySQL DSN required; this proof must not skip")
	}
	db := authzdb.Open(t, true)
	require.NoError(t, db.Exec(sdkmysql.Schema).Error)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	uow := authzuow.NewUnitOfWork(db, nil, authzdb.Stager(t, db))
	hostAbort := errors.New("host requested rollback")
	var committed message.Message
	for _, mode := range []string{"commit", "host-abort", "sdk-conflict"} {
		expectedVersion := int64(3)
		if mode == "commit" {
			expectedVersion = 2
		}
		evt := domainpolicy.NewVersionChangedEvent(expectedVersion) // Prepared once, not regenerated by an adapter.
		role, err := domainrole.NewRole("rm-proof-"+mode, mode)
		require.NoError(t, err)
		err = uow.WithinTx(ctx, func(txCtx context.Context, repos appuow.TxRepositories) error {
			if e := repos.Roles.Create(txCtx, &role); e != nil {
				return e
			}
			version, e := repos.PolicyVersions.Increment(txCtx, "rm-proof", mode)
			if e != nil {
				return e
			}
			if version.Version != expectedVersion {
				t.Fatalf("version %d", version.Version)
			}
			if e = repos.Events.Stage(txCtx, evt); e != nil {
				return e
			}
			original, e := dbmysql.RequireTx(txCtx)
			if e != nil {
				return e
			}
			appender, e := sdkmysql.BindGORM(original)
			if e != nil {
				return e
			}
			var row eventoutbox.OutboxPO
			if e = original.WithContext(txCtx).Where("event_id = ?", evt.EventID()).First(&row).Error; e != nil {
				return e
			}
			// Reuse persisted identity/time/raw payload, not a reconstructed envelope.
			intent, e := message.New(message.Input{Producer: "iam", ID: row.EventID, Destination: row.TopicName, EventType: row.EventType, SchemaVersion: "v2", Scope: "scope:global", ContentType: "application/json", OccurredAt: row.CreatedAt.UTC().Format(time.RFC3339Nano), Payload: []byte(row.PayloadJSON)})
			if e != nil {
				return e
			}
			if e = appender.Append(txCtx, intent, row.NextAttemptAt); e != nil {
				return e
			}
			if mode == "host-abort" {
				return hostAbort
			}
			if mode == "sdk-conflict" {
				changed := intent.Input()
				changed.Payload = []byte(`{"version":999}`)
				conflict, e := message.New(changed)
				if e != nil {
					return e
				}
				return appender.Append(txCtx, conflict, row.NextAttemptAt)
			}
			committed = intent
			return nil
		})
		switch mode {
		case "commit":
			require.NoError(t, err)
		case "host-abort":
			require.ErrorIs(t, err, hostAbort)
		case "sdk-conflict":
			require.ErrorIs(t, err, outbox.ErrConflict)
		}
	}
	var roles, legacy, intents int64
	require.NoError(t, db.Model(&rolerepo.RolePO{}).Count(&roles).Error)
	require.NoError(t, db.Model(&eventoutbox.OutboxPO{}).Count(&legacy).Error)
	require.NoError(t, db.Table("rm_outbox").Count(&intents).Error)
	require.EqualValues(t, 1, roles)
	require.EqualValues(t, 1, legacy)
	require.EqualValues(t, 1, intents)
	version, err := policyrepo.NewPolicyVersionRepository(db).GetCurrent(ctx)
	require.NoError(t, err)
	require.EqualValues(t, 2, version.Version)
	var row eventoutbox.OutboxPO
	require.NoError(t, db.First(&row).Error)
	require.Equal(t, `{"version":2}`, row.PayloadJSON)
	require.Equal(t, row.EventID, committed.Input().ID)
	require.Equal(t, row.PayloadJSON, string(committed.Input().Payload))
	sqlDB, err := db.DB()
	require.NoError(t, err)
	store, err := sdkmysql.New(sqlDB)
	require.NoError(t, err)
	claims, err := store.ClaimDue(ctx, 10, time.Minute)
	require.NoError(t, err)
	require.Len(t, claims, 1)
	require.Equal(t, committed.Fingerprint(), claims[0].Message.Fingerprint())
	require.NoError(t, store.Confirm(ctx, claims[0]))
}
